apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:

  name: vm-setup
  namespace: openshift-gitops

spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - name: '*'
      namespace: '*'
      server: 'https://kubernetes.default.svc'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'