kind: Secret
apiVersion: v1
metadata:
  name: git-repo-1
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    managed-by: argocd.argoproj.io
data:
  password: 
  project: 
  type: Z2l0
  url: 
  username: 
type: Opaque
